library(hessian)

hess <- function(rundir)
  hessian_serial(file.path("..", rundir), hessdir="../hessian")

hess("01_Diag2020/01c_Gradient")
hess("02_NewExe/02b_Version_2200")
hess("03_PreCatchCond/03h_Decrease_Move_Coeff_Penalty")
hess("04_CatchCond/04c_Catch_Cond_New_CPUE")
hess("05_Selectivity/05a_Allow_Decreasing_LL_Sel")
hess("06_TagStructure/06b_Remove_Groups_Five")
hess("07_Growth/07a_Fix_L1")
hess("08_Natmort/08a_Scaled_M")
hess("08_Natmort/08b_Lorenzen_M")
hess("08_Natmort/08c_Lorenzen_M_Init")
hess("09_CPUE_CV/09a_CPUE_CV_Lorenzen_M")
hess("09_CPUE_CV/09b_CPUE_CV_Lorenzen_M_Init")
hess("10_TaggerEffect/10a_Tagger_Effect_Lorenzen_M")
hess("10_TaggerEffect/10b_Tagger_Effect_Lorenzen_M_Init")
hess("11_SizeCompFilter/11a_Size_Comp_Filter_50")
hess("11_SizeCompFilter/11b_Size_Comp_Filter_100")
hess("12_NewData/12a_New_Data_0")
hess("12_NewData/12b_New_Data_50")
hess("12_NewData/12c_New_Data_100")
hess("13_TagMixing/13a_Tag_Mixing_1_Qtr_0")
hess("13_TagMixing/13b_Tag_Mixing_1_Qtr_50")
hess("13_TagMixing/13c_Tag_Mixing_1_Qtr_100")
hess("13_TagMixing/13d_Tag_Mixing_3_Qtr_0")
hess("13_TagMixing/13e_Tag_Mixing_3_Qtr_50")
hess("13_TagMixing/13f_Tag_Mixing_3_Qtr_100")

models <- readLines("93_create_hessdir.R")
models <- grep('^hess\\("', models, value=TRUE)
models <- gsub(".*?\"(.*?)\".*", "\\1", models)
models <- file.path("hessian", basename(models))

session <- ssh_connect("NOUOFPCALC02")

full_submit(models[1], "2.0.7.0", top.dir="hessian")
for(i in 2:length(models))
  full_submit(models[i], "2.2.0.0", top.dir="hessian")
